# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        EPSI\EventBundle\Entity\Administrateur:
            algorithm: bcrypt

    providers:
        admin:
            entity:
                class: EPSIEventBundle:Administrateur
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: admin
            logout:
                path:   /logout
                target: /
    access_control:
            # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
