<?php



namespace EPSI\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EPSI\EventBundle\Entity\Utilisateur;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function GetById(int $userId) : Utilisateur
    {
        $qb = $this->createQueryBuilder('utilisateur')
            ->where('utilisateur.id = :id')
            ->setParameter('id', $userId)
        ;
        $user = $qb->getQuery()->getOneOrNullResult();

        return (null === $user) ? new Utilisateur() : $user;
    }

    public function GetAllUsers() {

        return $this
            ->createQueryBuilder('utilisateur')
            ->getQuery()
            ->getResult();
    }
}
